---
site:
  title: Securing GenAI Applications with Guardrails as a Service
  url: https://github.com/rhpds/sec-genai-guardrails-showroom
  start_page: modules::workshop/guardrails/01-overview.adoc

content:
  sources:
    - url: .
      start_path: content

ui:
  bundle:
    url: https://github.com/rhpds/rhdp_showroom_theme/releases/download/showroom-template/ui-bundle.zip
    snapshot: true
  supplemental_files:
    - path: ./content/supplemental-ui
    - path: ./content/lib
    - path: .nojekyll
    - path: ui.yml
      contents: "static_files: [ .nojekyll ]"

antora:
  extensions:
    - require: ./content/lib/inject-buttons.js

asciidoc:
  attributes:
    showroom-collection-version: v1.5.2

output:
  dir: ./www
